### PR TITLE
Adding support for platform 2.x

### PR DESCRIPTION
**Pull request by dkayiwa**

### CODE REVIEW

**Comment by bholagabbar** [comment]
@dkayiwa Woah what's up :)

**Comment by dkayiwa** [comment]
@bholagabbar nothing much. wazup :)
I just noticed that a gci student got errors on running the module on his platform 2.x :)

**Comment by bholagabbar** [comment]
@dkayiwa I don't have my environment setup to test this. Have you tested it? Should I merge?

**Comment by dkayiwa** [comment]
@bholagabbar i usually do not commit before testing. :)
But that does not prevent you from having a second eye of testing if you can. :)

**Pull request merged**
